model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 512

exp_params:
  dataset: multicam
  data_path: "/home/rutav/dataset/multicam_hammer_dataset/"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  num_cam: 1

trainer_params:
  gpus: 1 
  max_nb_epochs: 50
  max_epochs: 50
  check_val_every_n_epoch: 1
  val_percent_check: 0.001

logging_params:
  save_dir: "/home/rutav/experiments_vae/"
  name: "multicam_hammer_top_512latentdim"
